import { useMemo } from 'react';


export const useRandomIcon = (uniqueKey: string) => {
  const pngs = [
    'icons/animals/color/parrot.png',
    'icons/animals/color/duck.png',
    'icons/animals/color/dog.png',
    'icons/animals/color/horse.png',
    'icons/animals/color/rabbit.png',
    'icons/animals/color/whale.png',
    'icons/animals/color/turtle.png',
    'icons/animals/color/rhinoceros.png',
    'icons/animals/color/beaver.png',
    'icons/animals/color/starfish.png',
    'icons/animals/color/deer.png',
    'icons/animals/color/elephant.png',
    'icons/animals/color/dolphin.png',
    'icons/animals/color/lion.png',
    'icons/animals/color/woodpecker.png',
    'icons/animals/color/seagull.png',
    'icons/animals/color/camel.png',
    'icons/animals/color/swan.png',
    'icons/animals/color/turkey.png',
    'icons/animals/color/flamingo.png',
    'icons/animals/color/rat.png',
    'icons/animals/color/octopus.png',
    'icons/animals/color/wildebeest.png',
    'icons/animals/color/zebra.png',
    'icons/animals/color/kangaroo.png',
    'icons/animals/color/chicken.png',
    'icons/animals/color/sheep.png',
    'icons/animals/color/lobster.png',
    'icons/animals/color/bird.png',
    'icons/animals/color/shark.png',
    'icons/animals/color/cow.png',
    'icons/animals/color/panda.png',
    'icons/animals/color/owl.png',
    'icons/animals/color/dinosaur.png',
    'icons/animals/color/peacock.png',
    'icons/animals/color/hummingbird.png',
    'icons/animals/color/wolf.png',
    'icons/animals/color/mouse.png',
    'icons/animals/color/squirrel.png',
    'icons/animals/color/cat.png',
    'icons/animals/color/goose.png',
    'icons/animals/color/frog.png',
    'icons/animals/color/hippopotamus.png',
    'icons/animals/color/lizard.png',
    'icons/animals/color/jellyfish.png',
    'icons/animals/color/crab.png',
    'icons/animals/color/bat.png',
    'icons/animals/color/seal.png',
    'icons/animals/color/giraffe.png',
    'icons/animals/color/fox.png',
    'icons/animals/color/pig.png',
    'icons/animals/color/alligator.png',
    'icons/animals/color/llama.png',
    'icons/animals/color/falcon.png',
    'icons/animals/color/badger.png',
    'icons/animals/color/snake.png',
    'icons/animals/color/bear.png',
    'icons/animals/color/walrus.png',
    'icons/animals/color/goat.png',
    'icons/animals/color/fish.png',
    'icons/animals/color/pelican.png',
    'icons/animals/color/hedgehog.png',
    'icons/fruits_and_vegetables/color/bok-choy.png',
    'icons/fruits_and_vegetables/color/mushroom.png',
    'icons/fruits_and_vegetables/color/kale.png',
    'icons/fruits_and_vegetables/color/raspberry.png',
    'icons/fruits_and_vegetables/color/peach.png',
    'icons/fruits_and_vegetables/color/grapefruit.png',
    'icons/fruits_and_vegetables/color/cauliflower.png',
    'icons/fruits_and_vegetables/color/zucchini.png',
    'icons/fruits_and_vegetables/color/apricot.png',
    'icons/fruits_and_vegetables/color/lime.png',
    'icons/fruits_and_vegetables/color/squash.png',
    'icons/fruits_and_vegetables/color/potato.png',
    'icons/fruits_and_vegetables/color/corn.png',
    'icons/fruits_and_vegetables/color/durian.png',
    'icons/fruits_and_vegetables/color/chard.png',
    'icons/fruits_and_vegetables/color/clementine.png',
    'icons/fruits_and_vegetables/color/coconut.png',
    'icons/fruits_and_vegetables/color/beet.png',
    'icons/fruits_and_vegetables/color/carrot.png',
    'icons/fruits_and_vegetables/color/blueberry.png',
    'icons/fruits_and_vegetables/color/pineapple.png',
    'icons/fruits_and_vegetables/color/celery.png',
    'icons/fruits_and_vegetables/color/artichoke.png',
    'icons/fruits_and_vegetables/color/ginger.png',
    'icons/fruits_and_vegetables/color/mango.png',
    'icons/fruits_and_vegetables/color/onion.png',
    'icons/fruits_and_vegetables/color/tomato.png',
    'icons/fruits_and_vegetables/color/asparagus.png',
    'icons/fruits_and_vegetables/color/watermelon.png',
    'icons/fruits_and_vegetables/color/cherry.png',
    'icons/fruits_and_vegetables/color/orange.png',
    'icons/fruits_and_vegetables/color/sweet-potato.png',
    'icons/fruits_and_vegetables/color/apple.png',
    'icons/fruits_and_vegetables/color/pomegranate.png',
    'icons/fruits_and_vegetables/color/blackberry.png',
    'icons/fruits_and_vegetables/color/date.png',
    'icons/fruits_and_vegetables/color/lychee.png',
    'icons/fruits_and_vegetables/color/kohlrabi.png',
    'icons/fruits_and_vegetables/color/garlic.png',
    'icons/fruits_and_vegetables/color/plantain.png',
    'icons/fruits_and_vegetables/color/pear.png',
    'icons/fruits_and_vegetables/color/avocado.png',
    'icons/fruits_and_vegetables/color/leek.png',
    'icons/fruits_and_vegetables/color/dragon-fruit.png',
    'icons/fruits_and_vegetables/color/collard-greens.png',
    'icons/fruits_and_vegetables/color/cucumber.png',
    'icons/fruits_and_vegetables/color/banana.png',
    'icons/fruits_and_vegetables/color/plum.png',
    'icons/fruits_and_vegetables/color/eggplant.png',
    'icons/fruits_and_vegetables/color/spinach.png',
    'icons/fruits_and_vegetables/color/cabbage.png',
    'icons/fruits_and_vegetables/color/strawberry.png',
    'icons/fruits_and_vegetables/color/lettuce.png',
    'icons/fruits_and_vegetables/color/jackfruit.png',
    'icons/fruits_and_vegetables/color/pumpkin.png',
    'icons/fruits_and_vegetables/color/radish.png',
    'icons/fruits_and_vegetables/color/kiwi.png',
    'icons/fruits_and_vegetables/color/soursop.png',
    'icons/fruits_and_vegetables/color/broccoli.png',
  ];
  
  
  return useMemo(() => {
    // Alternative hash function without bitwise operators
    let hash = 0;
    for (let i = 0; i < uniqueKey.length; i++) {
      hash = ((hash * 31) + uniqueKey.charCodeAt(i)) % 1000000007;
    }
    const index = Math.abs(hash) % pngs.length;
    return pngs[index];
  }, [uniqueKey]);
};