import { useMemo } from 'react';

export const useRandomIcon = (uniqueKey: string) => {
  const svgs = [
    'icons/food/icons8-bread-100.svg',
    'icons/food/icons8-kawaii-egg-100.svg',
    'icons/food/icons8-birthday-cake-100.svg',
    'icons/food/icons8-kawaii-steak-100.svg',
    'icons/food/icons8-banana-100.svg',
    'icons/food/icons8-watermelon-100.svg',
    'icons/food/icons8-whole-fish-100.svg',
    'icons/food/icons8-peas-100.svg',
    'icons/food/icons8-leek-100.svg',
    'icons/food/icons8-carrot-100.svg',
    'icons/food/icons8-prawn-100.svg',
    'icons/food/icons8-cake-100.svg',
    'icons/food/icons8-tapas-100.svg',
    'icons/food/icons8-kawaii-shellfish-100.svg',
    'icons/food/icons8-coconut-100.svg',
    'icons/food/icons8-blueberry-100.svg',
    'icons/food/icons8-kawaii-jam-100.svg',
    'icons/food/icons8-kawaii-noodle-100.svg',
    'icons/food/icons8-pastel-de-nata-100.svg',
    'icons/food/icons8-melting-ice-cream-100.svg',
    'icons/food/icons8-barbecue-100.svg',
    'icons/food/icons8-baguette-100.svg',
    'icons/food/icons8-ice-cream-sundae-100.svg',
    'icons/food/icons8-kawaii-pizza-100.svg',
    'icons/food/icons8-kawaii-milk-100.svg',
    'icons/food/icons8-brezel-100.svg',
    'icons/food/icons8-hot-dog-100.svg',
    'icons/food/icons8-melon-100.svg',
    'icons/food/icons8-rice-bowl-100.svg',
    'icons/food/icons8-sausages-100.svg',
    'icons/food/icons8-bread-loaf-100.svg',
    'icons/food/icons8-nachos-100.svg',
    'icons/food/icons8-doughnut-100.svg',
    'icons/food/icons8-yogurt-100.svg',
    'icons/food/icons8-fish-food-100.svg',
    'icons/food/icons8-cherry-100.svg',
    'icons/food/icons8-banana-split-100.svg',
    'icons/food/icons8-apple-fruit-100.svg',
    'icons/food/icons8-salad-100.svg',
    'icons/food/icons8-mango-100.svg',
    'icons/food/icons8-pineapple-100.svg',
    'icons/food/icons8-kawaii-ice-cream-100.svg',
    'icons/food/icons8-chocolate-bar-100.svg',
    'icons/food/icons8-pumpkin-100.svg',
    'icons/food/icons8-octopus-100.svg',
    'icons/food/icons8-strawberry-100.svg',
    'icons/food/icons8-corn-100.svg',
    'icons/food/icons8-kawaii-sushi-100.svg',
    'icons/food/icons8-grapes-100.svg',
    'icons/food/icons8-sunny-side-up-eggs-100.svg',
    'icons/food/icons8-cheese-100.svg',
    'icons/food/icons8-poultry-leg-100.svg',
    'icons/food/icons8-kawaii-cupcake-100.svg',
    'icons/food/icons8-citrus-100.svg',
    'icons/food/icons8-beet-100.svg',
    'icons/food/icons8-shellfish-100.svg',
    'icons/food/icons8-cotton-candy-100.svg',
    'icons/food/icons8-raspberry-100.svg',
    'icons/food/icons8-mushroom-100.svg',
    'icons/food/icons8-dragon-fruit-100.svg',
    'icons/food/icons8-dim-sum-100.svg',
    'icons/food/icons8-pancake-stack-100.svg',
    'icons/food/icons8-cute-pumpkin-100.svg',
    'icons/food/icons8-pizza-100.svg',
    'icons/food/icons8-kawaii-croissant-100.svg',
    'icons/food/icons8-chili-pepper-100.svg',
    'icons/food/icons8-candy-100.svg',
    'icons/food/icons8-bento-100.svg',
    'icons/food/icons8-cream-cheese-bagel-100.svg',
    'icons/food/icons8-jelly-100.svg',
    'icons/food/icons8-popcorn-100.svg',
    'icons/food/icons8-eggs-100.svg',
    'icons/food/icons8-hamburger-100.svg',
    'icons/food/icons8-kawaii-taco-100.svg',
    'icons/food/icons8-kawaii-coffee-100.svg',
    'icons/food/icons8-naan-100.svg',
    'icons/food/icons8-greek-salad-100.svg',
    'icons/food/icons8-kawaii-soda-100.svg',
    'icons/food/icons8-kawaii-french-fries-100.svg',
    'icons/food/icons8-pomegranate-100.svg',
    'icons/food/icons8-kawaii-bread-100.svg',
    'icons/food/icons8-durian-100.svg',
    'icons/food/icons8-jam-100.svg',
    'icons/food/icons8-sandwich-100.svg',
    'icons/food/icons8-noodles-100.svg',
    'icons/food/icons8-sausage-100.svg',
    'icons/food/icons8-crab-100.svg',
    'icons/food/icons8-tomato-100.svg',
    'icons/food/icons8-ice-cream-cone-100.svg',
    'icons/food/icons8-plum-100.svg',
    'icons/food/icons8-kawaii-broccoli-100.svg',
    'icons/food/icons8-salami-pizza-100.svg',
    'icons/food/icons8-lime-100.svg',
  ];

  return useMemo(() => {
    let hash = 0;
    for (let i = 0; i < uniqueKey.length; i++) {
      hash = ((hash * 31) + uniqueKey.charCodeAt(i)) % 1000000007;
    }
    const index = Math.abs(hash) % svgs.length;
    return svgs[index];
  }, [uniqueKey]);
};