import type { SheetConfig } from 'src/types';
import type { Template } from 'src/features/templates/types';

import { GridType, TraceContentMode } from 'src/types';
import { colors, candyColors } from 'src/theme/tokens';

export const chartraceTemplates: Template<SheetConfig>[] = [
  // ---------- 中文 ----------
  {
    id: 'chartrace-chars-tiandiren',
    titleKey: 'templates.chartrace.charsTiandiren.title',
    descKey: 'templates.chartrace.charsTiandiren.desc',
    config: {
      text: '天地人你我他',
      contentMode: TraceContentMode.CHARACTERS,
      gridType: GridType.TIAN,
      gridColor: colors.gridDefault,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-kaiti',
      mainTextColor: '#333333',
      traceTextColor: colors.traceDefault,
      traceOpacity: 0.5,
      rowsPerPage: 6,
      colsPerRow: 8,
      traceCount: 5,
      headerTitle: '天地人',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: true,
      showStrokeCount: true,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-phrases-riyueshanchuan',
    titleKey: 'templates.chartrace.phrasesRiyueshanchuan.title',
    descKey: 'templates.chartrace.phrasesRiyueshanchuan.desc',
    config: {
      text: '日月，山川，水火',
      contentMode: TraceContentMode.PHRASES,
      gridType: GridType.TIAN,
      gridColor: colors.gridDefault,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-kaiti',
      mainTextColor: '#333333',
      traceTextColor: colors.traceDefault,
      traceOpacity: 0.5,
      rowsPerPage: 6,
      colsPerRow: 8,
      traceCount: 1,
      headerTitle: '日月山川',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: true,
      showStrokeCount: true,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-sentences-jiangnan',
    titleKey: 'templates.chartrace.sentencesJiangnan.title',
    descKey: 'templates.chartrace.sentencesJiangnan.desc',
    config: {
      text: '江南可采莲，莲叶何田田。\n鱼戏莲叶间。',
      contentMode: TraceContentMode.SENTENCES,
      gridType: GridType.TIAN,
      gridColor: colors.gridDefault,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-kaiti',
      mainTextColor: '#333333',
      traceTextColor: colors.traceDefault,
      traceOpacity: 0.5,
      rowsPerPage: 6,
      colsPerRow: 8,
      traceCount: 1,
      headerTitle: '江南',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: true,
      showStrokeCount: true,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  // ---------- 英文 / 拼音 ----------
  {
    id: 'chartrace-pinyin-all',
    titleKey: 'templates.chartrace.pinyinAll.title',
    descKey: 'templates.chartrace.pinyinAll.desc',
    config: {
      text: 'b, p, m, f, d, t, n, l, g, k',
      contentMode: TraceContentMode.CHARACTERS,
      gridType: GridType.ENGLISH_LINES,
      gridColor: candyColors.red,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-english-print',
      mainTextColor: '#333333',
      traceTextColor: candyColors.red,
      traceOpacity: 0.5,
      rowsPerPage: 8,
      colsPerRow: 9,
      traceCount: 6,
      headerTitle: '汉语拼音描红',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: false,
      showStrokeCount: false,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-alphabet',
    titleKey: 'templates.chartrace.alphabet.title',
    descKey: 'templates.chartrace.alphabet.desc',
    config: {
      text: 'A, B, C, D, E, F, G, H, I, J',
      contentMode: TraceContentMode.CHARACTERS,
      gridType: GridType.ENGLISH_LINES,
      gridColor: candyColors.orange,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-english-print',
      mainTextColor: '#333333',
      traceTextColor: candyColors.orange,
      traceOpacity: 0.5,
      rowsPerPage: 8,
      colsPerRow: 9,
      traceCount: 6,
      headerTitle: 'Alphabet Tracing',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: false,
      showStrokeCount: false,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-english-numbers',
    titleKey: 'templates.chartrace.englishNumbers.title',
    descKey: 'templates.chartrace.englishNumbers.desc',
    config: {
      text: 'one, two, three, four, five, six, seven, eight, nine, ten',
      contentMode: TraceContentMode.CHARACTERS,
      gridType: GridType.ENGLISH_LINES,
      gridColor: candyColors.blue,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-english-print',
      mainTextColor: '#333333',
      traceTextColor: candyColors.blue,
      traceOpacity: 0.5,
      rowsPerPage: 8,
      colsPerRow: 9,
      traceCount: 3,
      headerTitle: 'Numbers',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: false,
      showStrokeCount: false,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'faded',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-english-colors',
    titleKey: 'templates.chartrace.englishColors.title',
    descKey: 'templates.chartrace.englishColors.desc',
    config: {
      text: 'red, blue, green, yellow, orange, purple, pink, brown, black, white',
      contentMode: TraceContentMode.CHARACTERS,
      gridType: GridType.ENGLISH_LINES,
      gridColor: candyColors.purple,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-english-print',
      mainTextColor: '#333333',
      traceTextColor: candyColors.purple,
      traceOpacity: 0.5,
      rowsPerPage: 8,
      colsPerRow: 9,
      traceCount: 2,
      headerTitle: 'Colors',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: false,
      showStrokeCount: false,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: true,
      traceMode: 'underline',
    },
    scale: 0.23,
  },
  {
    id: 'chartrace-english-sentences',
    titleKey: 'templates.chartrace.englishSentences.title',
    descKey: 'templates.chartrace.englishSentences.desc',
    config: {
      text: 'Hi, How are you?\nNice to meet you.',
      contentMode: TraceContentMode.SENTENCES,
      gridType: GridType.ENGLISH_LINES,
      gridColor: candyColors.purple,
      gridOpacity: 1,
      gridSize: 14,
      fontFamily: 'font-english-print',
      mainTextColor: '#333333',
      traceTextColor: candyColors.purple,
      traceOpacity: 0.5,
      rowsPerPage: 8,
      colsPerRow: 9,
      traceCount: 1,
      headerTitle: 'English Sentences',
      headerContent: '姓名: __________  日期: __________',
      showPinyin: false,
      showStrokeCount: false,
      showStrokeOrder: false,
      englishLineTheme: 'rainbow',
      showLineNumbers: false,
      traceMode: 'blank',
    },
    scale: 0.23,
  },
];
