import type { WorksheetConfig } from 'src/types';
import type { Template } from 'src/features/templates/types';

import {
  DisplayMode,
  ProblemType,
  MulDivLevel,
  OperationType,
  DifficultyLevel,
  ComparisonSubType,
  MultiOperationMode,
  SpecialPracticeType,
} from 'src/types';

import { calculateOptimalProblemsPerPage } from './shared/layout';

export const mathGenieTemplates: Template<WorksheetConfig>[] = [
  {
    id: 'math-genie-add-1-10',
    titleKey: 'templates.mathGenie.add110.title',
    descKey: 'templates.mathGenie.add110.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.ADDITION,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.NONE,
        operation: OperationType.ADDITION,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.NONE,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-mix-1-5-emoji',
    titleKey: 'templates.mathGenie.mix15Emoji.title',
    descKey: 'templates.mathGenie.mix15Emoji.desc',
    config: {
      theme: 'Fruits 🍎',
      difficulty: DifficultyLevel.CUSTOM,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.EMOJI,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.EMOJI,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.NONE,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.CUSTOM,
      }),
      customDifficulty: { min: 1, max: 5 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.NONE,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-mix-1-10-word',
    titleKey: 'templates.mathGenie.mix110Word.title',
    descKey: 'templates.mathGenie.mix110Word.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.WORD_PROBLEM,
      problemsPerPage: 4,
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.NONE,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-fill-mix-1-20',
    titleKey: 'templates.mathGenie.fillMix120.title',
    descKey: 'templates.mathGenie.fillMix120.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.CUSTOM,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 2,
        problemType: ProblemType.FILL_BLANK,
        specialPracticeType: SpecialPracticeType.NONE,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.CUSTOM,
      }),
      customDifficulty: { min: 1, max: 20 },
      problemType: ProblemType.FILL_BLANK,
      specialPracticeType: SpecialPracticeType.NONE,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-number-bond-1-10',
    titleKey: 'templates.mathGenie.numberBond110.title',
    descKey: 'templates.mathGenie.numberBond110.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.ADDITION,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.NUMBER_BOND,
        operation: OperationType.ADDITION,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.NUMBER_BOND,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-multi-op-mix-1-20',
    titleKey: 'templates.mathGenie.multiOpMix120.title',
    descKey: 'templates.mathGenie.multiOpMix120.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.CUSTOM,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 1,
        problemType: ProblemType.MULTI_STEP,
        specialPracticeType: SpecialPracticeType.NONE,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.CUSTOM,
      }),
      customDifficulty: { min: 1, max: 20 },
      problemType: ProblemType.MULTI_STEP,
      specialPracticeType: SpecialPracticeType.NONE,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-column-1-20',
    titleKey: 'templates.mathGenie.column120.title',
    descKey: 'templates.mathGenie.column120.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.CUSTOM,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 3,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 3,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.COLUMN_ARITHMETIC,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.CUSTOM,
      }),
      customDifficulty: { min: 1, max: 20 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.COLUMN_ARITHMETIC,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-column-1x2-mul',
    titleKey: 'templates.mathGenie.column1x2Mul.title',
    descKey: 'templates.mathGenie.column1x2Mul.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.MULTIPLICATION,
      count: 1,
      textColumns: 3,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 3,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.COLUMN_ARITHMETIC,
        operation: OperationType.MULTIPLICATION,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.COLUMN_ARITHMETIC,
      mulDivLevel: MulDivLevel.ONE_BY_TWO,
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-compare-1-10',
    titleKey: 'templates.mathGenie.compare110.title',
    descKey: 'templates.mathGenie.compare110.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.TEXT,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.TEXT,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.COMPARISON,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.COMPARISON,
      comparisonConfig: { subType: ComparisonSubType.MAGNITUDE },
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-compare-1-10-animals',
    titleKey: 'templates.mathGenie.compare110Animals.title',
    descKey: 'templates.mathGenie.compare110Animals.desc',
    config: {
      theme: 'Animals 🐶',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.EMOJI,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.EMOJI,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.COMPARISON,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.COMPARISON,
      comparisonConfig: { subType: ComparisonSubType.MAGNITUDE },
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
  {
    id: 'math-genie-compare-1-10-fruits',
    titleKey: 'templates.mathGenie.compare110Fruits.title',
    descKey: 'templates.mathGenie.compare110Fruits.desc',
    config: {
      theme: 'Fruits 🍎',
      difficulty: DifficultyLevel.EASY,
      operation: OperationType.MIXED,
      count: 1,
      textColumns: 2,
      title: 'Fun Math Time!',
      showAnswers: false,
      displayMode: DisplayMode.EMOJI,
      problemsPerPage: calculateOptimalProblemsPerPage({
        displayMode: DisplayMode.EMOJI,
        columns: 2,
        problemType: ProblemType.STANDARD,
        specialPracticeType: SpecialPracticeType.COMPARISON,
        operation: OperationType.MIXED,
        difficulty: DifficultyLevel.EASY,
      }),
      customDifficulty: { min: 1, max: 15 },
      problemType: ProblemType.STANDARD,
      specialPracticeType: SpecialPracticeType.COMPARISON,
      comparisonConfig: { subType: ComparisonSubType.DIFFERENCE },
      multiOperationConfig: { mode: MultiOperationMode.CHAIN_ADDITION, numberCount: 3 },
      excludeZeroProblems: false,
      autoPreview: true,
    },
    scale: 0.23,
  },
];
