import type { Template } from 'src/features/templates/types';

import { BlankMode } from './types';

import type { HundredChartConfig } from './types';

export const hundredChartTemplates: Template<HundredChartConfig>[] = [
  {
    id: 'hundred-chart-random-20',
    titleKey: 'templates.hundredChart.random20.title',
    descKey: 'templates.hundredChart.random20.desc',
    config: {
      mode: 'grid',
      pageTitle: '百数板填空',
      pageInfo: '姓名: __________  日期: __________',
      versionCount: 1,
      includeAnswerKey: false,
      startNumber: 1,
      blankMode: BlankMode.RANDOM,
      blankCount: 20,
      step: 5,
      offset: 0,
      manualBlanks: [],
      showFormula: true,
      showExample: true,
      showNumbering: true,
      minCenter: 11,
      maxCenter: 90,
      questionsPerPage: 8,
      columnsPerRow: 4,
      difficulty: 'medium',
      easyHintCount: 2,
      easyHintPosition: 'random',
      mediumCellCount: 'random5-6',
      mediumHintCount: 'random2-3',
      hardCellCount: 'random5-9',
    },
    scale: 0.23,
  },
  {
    id: 'hundred-chart-step5-offset1',
    titleKey: 'templates.hundredChart.step5Offset1.title',
    descKey: 'templates.hundredChart.step5Offset1.desc',
    config: {
      mode: 'grid',
      pageTitle: '百数板填空',
      pageInfo: '姓名: __________  日期: __________',
      versionCount: 1,
      includeAnswerKey: false,
      startNumber: 1,
      blankMode: BlankMode.PATTERN,
      blankCount: 20,
      step: 5,
      offset: 1,
      manualBlanks: [],
      showFormula: true,
      showExample: true,
      showNumbering: true,
      minCenter: 11,
      maxCenter: 90,
      questionsPerPage: 8,
      columnsPerRow: 4,
      difficulty: 'medium',
      easyHintCount: 2,
      easyHintPosition: 'random',
      mediumCellCount: 'random5-6',
      mediumHintCount: 'random2-3',
      hardCellCount: 'random5-9',
    },
    scale: 0.23,
  },
  {
    id: 'hundred-chart-cross-default',
    titleKey: 'templates.hundredChart.crossDefault.title',
    descKey: 'templates.hundredChart.crossDefault.desc',
    config: {
      mode: 'cross',
      pageTitle: '百数板填空',
      pageInfo: '姓名: __________  日期: __________',
      versionCount: 1,
      includeAnswerKey: false,
      startNumber: 1,
      blankMode: BlankMode.RANDOM,
      blankCount: 20,
      step: 5,
      offset: 0,
      manualBlanks: [],
      showFormula: true,
      showExample: true,
      showNumbering: true,
      minCenter: 11,
      maxCenter: 90,
      questionsPerPage: 8,
      columnsPerRow: 4,
      difficulty: 'medium',
      easyHintCount: 2,
      easyHintPosition: 'random',
      mediumCellCount: 'random5-6',
      mediumHintCount: 'random2-3',
      hardCellCount: 'random5-9',
    },
    scale: 0.23,
  },
];
